name: Utility
version: '${project.version}'
main: kileo.utility.Utility
api-version: 1.19
authors: [Leo13]
description: A plugin for general purposes.
commands:
  fly:
    description: Makes players fly.
    usage: /<command> [player]
    permission: utility.fly
  god:
    description: Makes people invunerable.
    usage: /<command> [player]
    permission: utility.god
  randomhotbar:
    description: Makes others' slot main hand completely random.
    usage: /<command> <player> <duration> <frequency>
    permission: utility.randomize.hotbar
permissions:
  utility.fly:
    description: Allows players to use fly command on themselves.
    default: op
  utility.fly.all:
    description: Allows players to use fly command on everyone.
    default: op
    children:
      - utility.fly
  utility.god:
    description: Allows players to use god command on themselves.
    default: op
  utility.god.all:
    description: Allows players to use god command on everyone.
    default: op
    children:
      - utility.god
  utility.randomize.hotbar:
    description: Allows players to randomize others' current item in main hand.
    default: op
  utility.randomize.hotbar.all:
    description: Allows to randomize everyone's current item in main hand.
    default: op
    children:
      - utility.randomize.hotbar